apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: hacbs-test-project-knvl
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: hacbs-test-project-knvl
    app.kubernetes.io/part-of: rhtap-demo-app
  name: hacbs-test-project-knvl
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: hacbs-jvm-build-test-project
      app.kubernetes.io/instance: hacbs-test-project-knvl
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: hacbs-jvm-build-test-project
        app.kubernetes.io/instance: hacbs-test-project-knvl
    spec:
      containers:
      - image: quay.io/redhat-appstudio-qe/rhtap-demo-erxf-tenant/rhtap-demo-app/hacbs-test-project-knvl@sha256:bd6b0cc095115733b1d3541cc2c710cabb9f3505719d2ed1eca30338c527707c
        name: hacbs-jvm-build-test-project
        ports:
        - containerPort: 8081
          name: http
          protocol: TCP
        resources:
          limits:
            cpu: 500m
            memory: 1Gi
status: {}
